# Generated by Django 4.1 on 2022-09-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0005_remove_participant_wallet_participant_user'),
        ('MemberSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cash_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
