# Generated by Django 4.1 on 2022-09-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
