# Generated by Django 4.1 on 2022-09-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberSystem', '0002_action_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
