# Generated by Django 4.1 on 2022-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberSystem', '0004_alter_action_target_alter_action_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_whitelist',
            field=models.BooleanField(default=False),
        ),
    ]
