# Generated by Django 4.1 on 2022-09-02 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contract_address', models.CharField(max_length=50)),
                ('plan_type', models.CharField(max_length=20)),
                ('fee', models.PositiveIntegerField()),
                ('launch_amount', models.PositiveIntegerField()),
                ('unlimited_period', models.BooleanField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('minimum_amounts', models.PositiveIntegerField()),
                ('minimum_participants', models.PositiveIntegerField()),
                ('benefits', models.CharField(max_length=20)),
                ('plan_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('join_date', models.DateField()),
                ('take_effect_date', models.DateField()),
                ('quit_date', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='Club.plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
