# Generated by Django 4.1 on 2022-08-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
