# Generated by Django 4.1 on 2022-09-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_alter_plan_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='quit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
