# Generated by Django 4.1 on 2022-09-05 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_participant_quitting'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 9, 5)),
        ),
    ]
