# Generated by Django 4.1 on 2022-09-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_alter_participant_quit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='wallet_address',
            new_name='wallet',
        ),
    ]
