# Generated by Django 4.1 on 2022-09-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MemberSystem', '0001_initial'),
        ('Club', '0004_rename_wallet_address_participant_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='wallet',
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='MemberSystem.userinfo'),
        ),
    ]
